kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

# Make sure we run for all events and branches
trigger:
  branch:
    - '*'  # Run on all branches
  event:
    - push
    - pull_request
    - custom  # Needed for manual triggers

steps:
  - name: debug-info
    image: node:16-alpine@arm64
    privileged: false
    settings:
      debug: true
    commands:
      - echo "Running pipeline on branch ${DRONE_BRANCH}"
      - env | grep DRONE

  - name: build
    image: docker:dind
    settings:
      debug: true
    privileged: false
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -t ground-station:latest .
      - docker run -d -p 6969:6969 --name ground-station-test ground-station:latest
      - sleep 10
      - curl -s http://localhost:6969 || echo "Container not responding"
      - docker stop ground-station-test
      - docker rm ground-station-test

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock