kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

trigger:
  branch:
    - main
  event:
    - push
    - pull_request
    - custom

clone:
  disable: true

steps:
  - name: clone
    image: plugins/git
    settings:
      depth: 50
      skip_verify: true

  - name: build
    image: docker:dind
    settings:
      debug: true
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      # Build the new image
      - docker build -t ground-station:latest .

      # Stop and remove existing container if it exists
      - docker rm -f ground-station-prod || true

      # Run the new container
      - docker run -d -p 7000:7000 --name ground-station-prod ground-station:latest

      # Wait for container to initialize
      - sleep 5

      # Health check using wget instead of curl (wget is often available in docker images)
      - apk add --no-cache wget || true
      - wget -q -O - http://localhost:7000 > /dev/null 2>&1 || (echo "Container not responding, trying alternative check" && docker logs ground-station-prod && exit 1)

      # Display container info
      - echo "✅ New container is running on host port 7000"
      - docker ps | grep ground-station-prod


volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock