kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

trigger:
  branch:
    - main
  event:
    - push
    - pull_request
    - tag
    - custom

clone:
  disable: true

steps:
  - name: clone
    image: plugins/git
    settings:
      depth: 50
      skip_verify: true
      tags: true

  - name: build-and-deploy
    image: docker:cli
    environment:
      DOCKER_HOST: tcp://192.168.60.98:2375
      DOCKER_USERNAME:
        from_secret: sgoudelis
      DOCKER_PASSWORD:
        from_secret: ZT97q#iJ6rDM
    commands:
      # Determine version
      - |
        if [ -n "$DRONE_TAG" ]; then
          # If this is a tagged build, use the tag
          VERSION=$DRONE_TAG
        else
          # Otherwise use branch-commit format
          GIT_SHA=$(git rev-parse --short HEAD)
          VERSION=${DRONE_BRANCH:-main}-$GIT_SHA
        fi
        echo "Building version: $VERSION"

      # Login to Docker Hub - fixed for non-TTY environment
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      # Build the new image for arm64
      - docker build --platform linux/arm64 -t ground-station:$VERSION .

      # Tag the image for Docker Hub
      - docker tag ground-station:$VERSION yourusername/ground-station:$VERSION
      - docker tag ground-station:$VERSION yourusername/ground-station:latest

      # Push to Docker Hub
      - docker push yourusername/ground-station:$VERSION
      - docker push yourusername/ground-station:latest

      # Stop and remove the existing container if it exists
      - docker rm -f ground-station-prod || true

      # Run the new container with the versioned image
      - docker run -d -p 0.0.0.0:7000:7000 --device=/dev/bus/usb --restart=unless-stopped --privileged --name ground-station-prod -v /media/pool1/volumes/ground-station-data:/app/backend/db yourusername/ground-station:$VERSION

      # Check that it's running
      - sleep 5
      - |
        CONTAINER_STATUS=$(docker inspect --format='{{.State.Status}}' ground-station-prod)
        if [ "$CONTAINER_STATUS" != "running" ]; then
          echo "Container is not running: $CONTAINER_STATUS"
          docker logs ground-station-prod
          exit 1
        fi

      # Display container info and version
      - echo "✅ New container version $VERSION is running on host port 7000"
      - docker ps | grep ground-station-prod

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock